name: Terraform CI

on:
  push:
    branches-ignore:
      - main    # excludes main branch
  workflow_dispatch:
permissions:
  id-token: write
  contents: read

concurrency: 
  group: terraform-${{ github.event.repository.name }}
  cancel-in-progress: false

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    environment: plan
    env:
      ARM_CLIENT_ID: "${{ vars.AZURE_CLIENT_ID }}"
      ARM_SUBSCRIPTION_ID: "${{ vars.AZURE_SUBSCRIPTION_ID }}"
      ARM_TENANT_ID: "${{ vars.AZURE_TENANT_ID }}"
      ARM_USE_AZUREAD: true
      ARM_USE_OIDC: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Setup TfLint
        uses: terraform-linters/setup-tflint@v4

      - name: Run TFLint
        run: tflint --chdir=tf/ -f compact

      - name: Terraform Format Check
        run: terraform -chdir=./tf fmt -recursive -check

      - name: Terraform Init
        run: terraform -chdir=./tf init -backend=false

      - name: Terraform Validate
        run: terraform -chdir=./tf validate

      - name: Terraform Init full 
        run: |
          terraform -chdir=./tf init \
            -backend-config="storage_account_name=${{ vars.BACKEND_AZURE_STORAGE_ACCOUNT_NAME }}" \
            -backend-config="container_name=${{ vars.BACKEND_AZURE_STORAGE_ACCOUNT_CONTAINER_NAME }}" \
            -backend-config="resource_group_name=${{ vars.BACKEND_AZURE_RESOURCE_GROUP_NAME }}" \
            -backend-config="key=terraform.tfstate"

      - name: Terraform Plan
        run: |
          # shellcheck disable=SC2086
          terraform -chdir=./tf plan -out=tfplan -input=false

      - name: Show the Plan for Review
        run: terraform -chdir=./tf show tfplan
 